# Jekyll configuration file
title: "Rachel Park's Personal Portfolio"
author: "Rachel"
email: "racheliee.dwg@gmail.com"
description: "CSE & IE @ skku"
baseurl: "" # for user/organization site, leave this empty
url: "https://racheliee.github.io" # the base hostname & protocol for your site
favicon-url: "/assets/images/favicon.ico"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Hero image
hero-image: "https://unsplash.com/photos/black-and-white-computer-keyboard-4IxPVkFGJGI"

# Author info
author-name: "Rachel Park"
author-image: "/assets/images/profile-picture.jpg"
author-bio: "I'm currently a student studying industrial engineering and computer science at SKKU. Take a look at my projects and feel free to reach out to me!"

# Tech stack
tech-stack:
  - C
  - Python
  - Spring Boot
  - Java
  - Rust

# Resume
resume-path: "/assets/files/resume.pdf"

# Education
education:
  - degree: "Bachelor of Science in Computer Science"
    institution: "Sungkyunkwan University"
    date: "2020 - 2024"
    description: "Focused on software engineering and data science."
  - degree: "High School Diploma"
    institution: "Seoul Science High School"
    date: "2017 - 2020"
    description: "Specialized in mathematics and science."


# Experiences
experiences:
  - position: "Software Engineering Intern"
    company: "Tech Company"
    date: "June 2023 - August 2023"
    description: "Worked on developing and optimizing backend services using Java and Spring Boot."
  - position: "Research Assistant"
    company: "University Lab"
    date: "January 2022 - May 2023"
    description: "Assisted in research on machine learning algorithms and their applications in real-world scenarios."
  - position: "Web Developer"
    company: "Freelance"
    date: "March 2021 - December 2021"
    description: "Developed and maintained several websites for local businesses using HTML, CSS, and JavaScript."


# Exclude from processing.
include:
  - _pages
exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - .sass-cache/
  - .jekyll-cache/
