title: "Racheliee's Portfolio"
author: "Rachel"
email: "racheliee.dwg@gmail.com"
description: "A description of your site"
baseurl: "" # for user/organization site, leave this empty
url: "https://racheliee.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

include:
  - _pages
exclude:
  - node_modules
